// Acronyms used by gls()/glspl()/glsshort().
// gls("os") expands on first use, then prints the short form; glsshort never expands.
#let glossary = (
  "os":     (short: "OS",    long: "Operating System"),
  "smp":    (short: "SMP",   long: "Symmetric Multiprocessing"),
  "cpu":    (short: "CPU",   long: "Central Processing Unit"),
  "mmu":    (short: "MMU",   long: "Memory Management Unit"),
  "tlb":    (short: "TLB",   long: "Translation Lookaside Buffer"),
  "numa":   (short: "NUMA",  long: "Non-Uniform Memory Access"),
  "cfs":    (short: "CFS",   long: "Completely Fair Scheduler"),
  "rcu":    (short: "RCU",   long: "Read-Copy-Update"),
  "ebpf":   (short: "eBPF",  long: "extended Berkeley Packet Filter"),
  "vfs":    (short: "VFS",   long: "Virtual File System"),
  "dma":    (short: "DMA",   long: "Direct Memory Access"),
  "irq":    (short: "IRQ",   long: "Interrupt Request"),
  "api":    (short: "API",   long: "Application Programming Interface"),
  "abi":    (short: "ABI",   long: "Application Binary Interface"),
  "vm":     (short: "VM",    long: "Virtual Machine"),
  "lru":    (short: "LRU",   long: "Least Recently Used"),
  "pid":    (short: "PID",   long: "Process Identifier"),
  "ipc":    (short: "IPC",   long: "Inter-Process Communication"),
  "nic":    (short: "NIC",   long: "Network Interface Card"),
  "ssd":    (short: "SSD",   long: "Solid-State Drive"),
  "iommu":  (short: "IOMMU", long: "Input-Output Memory Management Unit"),
  "qemu":   (short: "QEMU",  long: "Quick Emulator"),
  "posix":  (short: "POSIX", long: "Portable Operating System Interface"),
  "slab":   (short: "SLUB",  long: "Slab Unqueued Allocator"),
  "hpc":    (short: "HPC",   long: "High-Performance Computing"),
)
